### ISSUE TITLE
Build environment

### ISSUE THREAD

**Issue by bbaltz505** [arduino/dfu-utils-cross#1]
Hi.
Have you built this on Ubuntu 12.04? I have issues with libusb when building on 12.04:

<pre>
.../dfu-utils-cross/libusb-1.0.9/libusb/.libs//libusb-1.0.a(libusb_1_0_la-linux_usbfs.o): In function `find_monotonic_clock':
.../dfu-utils-cross/libusb-1.0.9/libusb/os/linux_usbfs.c:262: undefined reference to `clock_gettime'
</pre>

It seems older GCC versions (2.17) needs the -lrt flag.

Brian

**Comment by facchinm** [comment]
Hi Brian,
it's possible, the binaries were compiled on Ubuntu 14.04.
Feel free to add the flag if you wish to support a wider audience

**Comment by bbaltz505** [comment]
Ok. Thanks.
